version: "3.9"
services:
  worker:
    build:
    environment:
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      AUTH_CHANNEL: $AUTH_CHANNEL
      OWNER_ID: $OWNER_ID
      UPLOAD_AS_DOC: $UPLOAD_AS_DOC
      CHUNK_SIZE: $CHUNK_SIZE
      ARIA_TWO_STARTED_PORT: $ARIA_TWO_STARTED_PORT
      EDIT_SLEEP_TIME_OUT: $EDIT_SLEEP_TIME_OUT
      MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START: $MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START
      FINISHED_PROGRESS_STR: $FINISHED_PROGRESS_STR
      UN_FINISHED_PROGRESS_STR: $UN_FINISHED_PROGRESS_STR
      TG_OFFENSIVE_API: $TG_OFFENSIVE_API
      LEECH_COMMAND: $LEECH_COMMAND
      SAVE_THUMBNAIL: $SAVE_THUMBNAIL
      CLEAR_THUMBNAIL: $CLEAR_THUMBNAIL
      INDEX_LINK: $INDEX_LINK
      GLEECH_COMMAND: $GLEECH_COMMAND
      TELEGRAM_LEECH_COMMAND_G: $TELEGRAM_LEECH_COMMAND_G
      YTDL_COMMAND: $YTDL_COMMAND
      PYTDL_COMMAND_G: $PYTDL_COMMAND_G
      CANCEL_COMMAND_G: $CANCEL_COMMAND_G
      GET_SIZE_G: $GET_SIZE_G
      RCLONE_CONFIG: $RCLONE_CONFIG
      DESTINATION_FOLDER: $DESTINATION_FOLDER
      CUSTOM_FILE_NAME: $CUSTOM_FILE_NAME
      
      
      
     
